# These are supported funding model platforms

# github: [sheikhabirali]  # uncomment if you join GitHub Sponsors
# ko_fi: sheikhabirali      # uncomment if you set up Ko-fi
custom: https://sheikhabirali.netlify.app/
